# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cogitarelink-dspy',
                'doc_host': 'https://LA3D.github.io',
                'git_url': 'https://github.com/LA3D/cogitarelink-dspy',
                'lib_path': 'cogitarelink_dspy'},
  'syms': { 'cogitarelink_dspy.components': { 'cogitarelink_dspy.components.get_tools_by_layer': ( 'components.html#get_tools_by_layer',
                                                                                                   'cogitarelink_dspy/components.py'),
                                              'cogitarelink_dspy.components.list_layers': ( 'components.html#list_layers',
                                                                                            'cogitarelink_dspy/components.py'),
                                              'cogitarelink_dspy.components.validate_component_registry': ( 'components.html#validate_component_registry',
                                                                                                            'cogitarelink_dspy/components.py')},
            'cogitarelink_dspy.core': { 'cogitarelink_dspy.core.Echo': ('core.html#echo', 'cogitarelink_dspy/core.py'),
                                        'cogitarelink_dspy.core.Echo.forward': ('core.html#echo.forward', 'cogitarelink_dspy/core.py'),
                                        'cogitarelink_dspy.core.make_hello_agent': ( 'core.html#make_hello_agent',
                                                                                     'cogitarelink_dspy/core.py')},
            'cogitarelink_dspy.wrappers': {'cogitarelink_dspy.wrappers.foo': ('wrappers.html#foo', 'cogitarelink_dspy/wrappers.py')}}}
