# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cogitarelink-dspy',
                'doc_host': 'https://LA3D.github.io',
                'git_url': 'https://github.com/LA3D/cogitarelink-dspy',
                'lib_path': 'cogitarelink_dspy'},
  'syms': { 'cogitarelink_dspy.core': {'cogitarelink_dspy.core.foo': ('core.html#foo', 'cogitarelink_dspy/core.py')},
            'cogitarelink_dspy.wrappers': {'cogitarelink_dspy.wrappers.foo': ('wrappers.html#foo', 'cogitarelink_dspy/wrappers.py')}}}
