"""A minimal DSPy agent implementation to echo or compute simple inputs."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['Echo', 'make_hello_agent']

# %% ../nbs/00_core.ipynb 3
import dspy

class Echo(dspy.Module):
    """Echoes the input message back."""
    def forward(self, message: str) -> str:
        return message

# %% ../nbs/00_core.ipynb 4
def make_hello_agent(llm=None):
    """Create a simple DSPy agent with the Echo tool."""
    # Create an Agent class that uses the Echo tool
    class HelloAgent(dspy.Module):
        def __init__(self):
            super().__init__()
            self.tools = [Echo()]
            
        def forward(self, message):
            # Simply use the Echo tool to echo the message back
            echo_tool = self.tools[0]
            return echo_tool.forward(message)
            
    # Return a new instance of the HelloAgent
    return HelloAgent()
